version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/ozgio/strutil
    steps:
      - checkout
      - run: go get github.com/stretchr/testify/assert
      - run: go test .
      - run: go vet .
      
